const items = [
  {
    id: 0,
    img: "./Store/bs739-image-kwvx4zfu.jpg",
    name: "Black Shoes Lights",
    price: "155.39",
    category: "shoes",
  },
  {
    id: 1,
    img: "./Store/hogan_hyperactive_nero_leopardo_2.jpg",
    name: "Black Shoes Military",
    price: "189.00",
    category: "shoes",
  },
  {
    id: 2,
    img: "./Store/unisex pants.jpg",
    name: "Plus Size Pants",
    price: "383.99",
    category: "pants",
  },
  {
    id: 3,
    img: "./Store/T-Shirt_Wikipedia_black.jpg",
    name: "Wikipedia Black Shirt",
    price: "35.39",
    category: "shirt",
  },
  {
    id: 4,
    img: "./Store/pants (2).jpg",
    name: "Kaki Pants",
    price: "55.99",
    category: "pants",
  },
  {
    id: 5,
    img: "./Store/shows woman hels.jpg",
    name: "Heels Shoes American Flag",
    price: "189.42",
    category: "shoes",
  },
  {
    id: 16,
    img: "./Store/shirt.jpg",
    name: "Red Shirt",
    price: "102.92",
    category: "shirt",
  },

  {
    id: 6,
    img: "./Store/pants a.jpg",
    name: "Kaki Pants",
    price: "142.49",
    category: "pants",
  },
  {
    id: 7,
    img: "./Store/shoes.jpg",
    name: "Heels Panna",
    price: "225.19",
    category: "shoes",
  },
  {
    id: 8,
    img: "./Store/pants man.jpg",
    name: "Other kaki pants",
    price: "257.91",
    category: "pants",
  },
  {
    id: 9,
    img: "./Store/shoes woman.jpg",
    name: "Women's sports shoes",
    price: "89.00",
    category: "shoes",
  },
  {
    id: 10,
    img: "./Store/pants womand.jpg",
    name: "Some More kaki pants",
    price: "283.99",
    category: "pants",
  },
  {
    id: 11,
    img: "./Store/pants woman.jpg",
    name: "Womens Jogging",
    price: "301.93",
    category: "pants",
  },
  {
    id: 12,
    img: "./Store/shirt (2).jpg",
    name: "Cute Shirt Beaver",
    price: "91.22",
    category: "shirt",
  },
  {
    id: 13,
    img: "./Store/shirt (3).jpg",
    name: "Shirt of lies",
    price: "291.42",
    category: "shirt",
  },
  {
    id: 14,
    img: "./Store/shirt (4).jpg",
    name: "Blue Adventure time shirt",
    price: "41.98",
    category: "shirt",
  },
  {
    id: 15,
    img: "./Store/shirt (1).jpg",
    name: "Tech Shirt",
    price: "98.92",
    category: "shirt",
  },
  {
    id: 17,
    img: "./Store/new Shoes.jpg",
    name: "Black White Shoes",
    price: "159.18",
    category: "shoes",
  },
  {
    id: 18,
    img: "./Store/new shoes 2.jpg",
    name: "High Platform Shoes",
    price: "278.62",
    category: "shoes",
  },
];

export default items;
